import type { Metadata } from "next";
import  "../globals.css"
import LeftBar from  "../components/LeftBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


      

     <div className="flex min-h-screen">
            {/* Sol Sabit Sidebar */}
            <aside className=" w-64 bg-indigo-800 text-white h-screen flex-shrink-0">
              <LeftBar />
            </aside>

            {/* Sayfa içeriği */}
            <main className="flex-1  bg-gray-100 overflow-auto ">
              {children}
            </main>
          </div>
   
  );
}
