import type { Metadata } from "next";
import  "../globals.css"
import { UserProvider } from "../context/UserContext";
import LeftBar from  "../components/LeftBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


      <UserProvider>

     <div className="flex min-h-screen">
            {/* Sol Sabit Sidebar */}
            <aside className=" w-1/5  bg-white  border-gray-200 hidden md:block">
              <LeftBar />
            </aside>

            {/* Sayfa içeriği */}
            <main className="flex-1  bg-gray-100 overflow-auto p-4">
              {children}
            </main>
          </div>
  </UserProvider>
   
  );
}
