import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import LeftBar from "./components/LeftBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-white text-black dark:bg-black dark:text-white">

      <UserProvider>

     <div className="flex min-h-screen">
            {/* Sol Sabit Sidebar */}
            <aside className=" w-1/5  bg-white  border-gray-200 hidden md:block">
              <LeftBar />
            </aside>

            {/* Sayfa içeriği */}
            <main className="flex-1  bg-gray-100 overflow-auto p-4">
              {children}
            </main>
          </div>
  </UserProvider>
      </body>
    </html>
  );
}
